version: '3'
services:
  app:
    container_name: nginx
    hostname: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '10080:80'
      - '10081:81'
      - '10443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  default:
    name: nginx
