---
- name: Update cache
  ansible.builtin.package:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    force_apt_get: true
