---
- name: Install Node.js
  remote_user: vineel
  become: false
  ansible.builtin.shell:
    chdir: ~
    cmd: |
      vmn node install lts
      vmn node use lts

- name: Install Python
  remote_user: vineel
  become: false
  ansible.builtin.shell:
    chdir: ~
    cmd: |
      vmn python install 3.12
      vmn python use 3.12
