---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  selector:
    matchLabels:
      app: discord-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
        searches: []
      containers:
        - name: discord-bot
          image: vineelsai/discord-bot:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: TOKEN
