version: "3.4"
services:
  tdarr:
    container_name: tdarr
    hostname: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    privileged: true
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ./tdarr/logs:/app/logs
      - ./tdarr/media:/media
      - ./tdarr/transcode_cache:/temp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.entrypoints=http"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.home.vineelsai.com`)||Host(`tdarr.vineelsai.com`)"
      - "traefik.http.middlewares.tdarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tdarr.middlewares=tdarr-https-redirect"
      - "traefik.http.routers.tdarr-secure.entrypoints=https"
      - "traefik.http.routers.tdarr-secure.rule=Host(`tdarr.home.vineelsai.com`)||Host(`tdarr.vineelsai.com`)"
      - "traefik.http.routers.tdarr-secure.tls=true"
      - "traefik.http.routers.tdarr-secure.service=tdarr"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
      - "traefik.docker.network=proxy"

  # tdarr_node:
  #   container_name: tdarr_node
  #   hostname: tdarr_node
  #   image: ghcr.io/haveagitgat/tdarr_node:latest
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Asia/Kolkata
  #     - PUID=1001
  #     - PGID=1001
  #     - UMASK_SET=002
  #     - nodeName=MyExternalNode
  #     - serverIP=100.93.40.74
  #     - serverPort=8266
  #     - inContainer=true
  #     - ffmpegVersion=6
  #   volumes:
  #     - ./tdarr/configs:/app/configs
  #     - ./tdarr/logs:/app/logs
  #     - ./tdarr/media:/media
  #     - ./tdarr/transcode_cache:/temp

networks:
  default:
    name: traefik_proxy
    external: true
