version: '3'

services:
  postgres_gitea:
    container_name: postgres_gitea
    hostname: postgres_gitea
    image: postgres:14
    restart: always
    volumes:
      - ./data/postgres_gitea:/var/lib/postgresql/data
    env_file:
      - env/gitea.env
      - env/creds.env

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - env/semaphore.env
      - env/creds.env

networks:
  default:
    name: traefik_proxy
    external: true
