version: '3'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:27.1.4-fpm-alpine
    restart: always
    volumes:
      - ./html:/var/www/html
    env_file:
      - .env
  server:
    container_name: nextcloud_nginx
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.home.vineelsai.com`)||Host(`nextcloud.vineelsai.com`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.home.vineelsai.com`)||Host(`nextcloud.vineelsai.com`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  default:
    name: traefik_proxy
    external: true
