version: "3"
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:1.6.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: traefik_proxy
    external: true
