version: '3'
services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    hostname: homeassistant
    privileged: true
    volumes:
      - homeassistant_config:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped

volumes:
  homeassistant_config:
    name: homeassistant_config
