version: '3'
services:
  shortify:
    hostname: shortify
    image: 'vineelsai/shortify:latest'
    ports:
      - '3100:3000'
    env_file:
      - env/shortify.env
    command: ./shortify
    deploy:
      placement:
        constraints:
          - node.role==worker

networks:
  default:
    name: traefik_overlay_proxy
    external: true
