http:
  routers:
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.home.vineelsai.com`)"
      middlewares:
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole

    homeassistant:
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.home.vineelsai.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homeassistant

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.0.2:80"
        passHostHeader: true

    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.0.0.4:8123"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
          - default-headers
