http:
  routers:
    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.home.vineelsai.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: nextcloud

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.0.0.10:8080"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
          - default-headers
