http:
  routers:
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.home.vineelsai.com`)"
      middlewares:
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
    homeassistant:
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.home.vineelsai.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homeassistant

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.10.53:80"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.0.10.48:8123"
        passHostHeader: true
    pve:
      loadBalancer:
        servers:
          - url: "https://10.0.10.10:8006"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://10.0.10.20"
        passHostHeader: true
    pi4:
      loadBalancer:
        servers:
          - url: "https://10.0.10.4:9090"
        passHostHeader: true
    pfsense:
      loadBalancer:
        servers:
          - url: "https://10.0.10.1"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
          - default-headers
