---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-vineelsai-com
  namespace: default
spec:
  secretName: local-vineelsai-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.vineelsai.com"
  dnsNames:
    - "local.vineelsai.com"
    - "*.local.vineelsai.com"
