version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=0
      - PGID=0
      - DOMAIN=syncthing.home.vineelsai.com
      - HOME=/var/syncthing
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ./syncthing/config:/var/syncthing/config
      - ./syncthing:/var/syncthing
      - /home/vineel:/var/syncthing/vineel:ro
    network_mode: host
    restart: unless-stopped
