version: '3'
services:
  app:
    container_name: portainer
    hostname: portainer
    image: 'portainer/portainer-ee:latest'
    restart: unless-stopped
    ports:
      - '9443:9443'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"

networks:
  default:
    name: nginx
    external: true
