version: '3'
services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: 'portainer/portainer-ee:2.19.1'
    restart: unless-stopped
    ports:
      - '9443:9443'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.home.vineelsai.com`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.home.vineelsai.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"

networks:
  default:
    name: traefik_proxy
    external: true
