services:
  bitwarden:
    container_name: bitwarden
    hostname: bitwarden
    image: ${REGISTRY:-bitwarden}/self-host:${TAG:-beta}
    restart: unless-stopped
    ports:
      - '2080:2080'
      - '2443:2443'
    volumes:
      - ./bitwarden/data:/etc/bitwarden
      - ./bitwarden/logs:/var/log/bitwarden
    env_file:
      - env/creds.env
      - env/settings.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.home.vineelsai.com`)||Host(`bitwarden.vineelsai.com`)"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bitwarden.home.vineelsai.com`)||Host(`bitwarden.vineelsai.com`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=2080"
      - "traefik.docker.network=traefik_proxy"

networks:
  default:
    name: traefik_proxy
    external: true
