version: '3'
services:
  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden
    image: 'vaultwarden/server:1.30.5'
    restart: unless-stopped
    ports:
      - '2080:80'
    volumes:
      - ./data/:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.home.vineelsai.com`)"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bitwarden.home.vineelsai.com`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"

networks:
  default:
    name: traefik_proxy
    external: true
