services:
  cloudflare:
    image: 'cloudflare/cloudflared:2023.10.0'
    container_name: cloudflared
    hostname: cloudflared
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    env_file:
      - .env

networks:
  default:
    name: traefik_proxy
    external: true
