version: '3'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  default:
    name: traefik_proxy
    external: true
