services:
  discord_bot:
    container_name: discord-bot
    hostname: discord-bot
    image: 'vineelsai/discord-bot:latest'
    restart: unless-stopped
    env_file:
      - .env

networks:
  default:
    name: traefik_proxy
    external: true
