version: '3'
services:
  discord_bot:
    hostname: discord-bot
    image: 'vineelsai/discord-bot:latest'
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role==worker

networks:
  default:
    name: discord_bot_network
