http:
  routers:
    gitea:
      entryPoints:
        - "https"
      rule: "Host(`gitea.vineelsai.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - url: "https://gitea.home.vineeelsai.com"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
          - default-headers
